# Generated by Django 2.2.6 on 2019-10-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pintecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='location',
        ),
    ]
