# Generated by Django 2.2.6 on 2019-10-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintecipeApp', '0003_auto_20191005_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='input',
            field=models.TextField(default='inputText', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='comment',
            field=models.TextField(max_length=60),
        ),
    ]
