# Generated by Django 2.2.6 on 2019-10-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pintecipeApp', '0004_auto_20191005_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='input',
            new_name='inputText',
        ),
    ]
