# Generated by Django 2.2.6 on 2019-10-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pintecipeApp', '0005_auto_20191005_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='inputText',
        ),
    ]
