# Generated by Django 2.2.6 on 2019-10-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintecipeApp', '0006_remove_ingredient_inputtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='inputText',
            field=models.TextField(default='input text from api', max_length=200),
            preserve_default=False,
        ),
    ]
