# Generated by Django 2.2.6 on 2019-10-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintecipeApp', '0008_auto_20191005_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredientInput',
            new_name='input',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeLink',
            field=models.URLField(default='recipeLink'),
            preserve_default=False,
        ),
    ]
