# Generated by Django 2.2.6 on 2019-10-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintecipeApp', '0009_auto_20191005_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='comment',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
