# Generated by Django 2.2.6 on 2019-10-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pintecipeApp', '0011_auto_20191008_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
